### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by spotlesscoder** [jspaine/zxing.js#2]
I can't figure out how to use this. When I go to the live demo with latest chrome or firefox.

I just get the message "getUserMedia not supported in this browser: NotFoundError: Requested device not found"

**Comment by jspaine** [comment]
On desktop? Mobile browsers don't allow use of the camera.

**Comment by spotlesscoder** [comment]
Ah ok, it's meant for mobile phone use. Didn't recognize that

**Comment by jspaine** [comment]
No it doesn't work on phones. On desktop you need a webcam and to give the page permission to use it. Otherwise I'm not sure why you're getting that error.

**Comment by spotlesscoder** [comment]
Oh ok.
I don't have a webcam
